name: evently_app

# description: "A new Flutter project."
# # The following line prevents the package from being accidentally published to
# # pub.dev using `flutter pub publish`. This is preferred for private packages.
# publish_to: 'none' # Remove this line if you wish to publish to pub.dev


# version: 1.0.0+1

# environment:
#   sdk: ^3.5.3


# dependencies:
#   flutter:
#     sdk: flutter
#   flutter_localizations:
#     sdk: flutter
#   flutter_gen: ^5.9.0


#   # The following adds the Cupertino Icons font to your application.
#   # Use with the CupertinoIcons class for iOS style icons.
#   cupertino_icons: ^1.0.8
#   firebase_core: ^3.10.0
#   firebase_auth: ^5.4.0
#   flutter_easyloading: ^3.0.5
#   bot_toast: ^4.1.3
#   lottie: ^3.2.0
#   flutter_svg:
#   cloud_firestore: ^5.6.2
#   shared_preferences: ^2.4.0
#   intl:
#   animated_custom_dropdown: ^3.1.1
#   provider: ^6.1.2
#   smooth_page_indicator: ^1.2.0+3
#   google_sign_in: ^6.2.2
#   font_awesome_flutter: ^10.8.0
#   geolocator: ^13.0.2
#   flutter_localization: ^0.3.1
#   # firebase_messaging: ^15.2.2
#   # flutter_local_notifications: ^18.0.1

# dev_dependencies:
#   flutter_test:
#     sdk: flutter


#   # The "flutter_lints" package below contains a set of recommended lints to
#   # encourage good coding practices. The lint set provided by the package is
#   # activated in the `analysis_options.yaml` file located at the root of your
#   # package. See that file for information about deactivating specific lint
#   # rules and activating additional ones.
#   flutter_lints: ^4.0.0



# # The following section is specific to Flutter packages.
# flutter:


#   generate: true 
#   uses-material-design: true

#   assets:
#     - assets/images/
#     - assets/icons/
#     - assets/fonts/
#     - assets/translations/

#   fonts:
#     - family: "Inter"
#       fonts:
#         - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
#         - asset: assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  firebase_core: ^3.10.0
  firebase_auth: ^5.4.0
  flutter_easyloading: ^3.0.5
  bot_toast: ^4.1.3
  lottie: ^3.2.0
  flutter_svg:
  cloud_firestore: ^5.6.2
  shared_preferences: ^2.4.0
  intl:
  animated_custom_dropdown: ^3.1.1
  provider: ^6.1.2
  smooth_page_indicator: ^1.2.0+3
  google_sign_in: ^6.2.2
  font_awesome_flutter: ^10.8.0
  geolocator: ^13.0.2
  location: ^8.0.0
  google_maps_flutter: ^2.10.0
  permission_handler: ^11.3.1
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter


  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^4.0.0



# The following section is specific to Flutter packages.
flutter:


  generate: true 
  uses-material-design: true

  assets:
    - assets/images/
    - assets/icons/
    - assets/fonts/
    - assets/map_styles/

  fonts:
    - family: "Inter"
      fonts:
        - asset: assets/fonts/Inter-VariableFont_opsz,wght.ttf
        - asset: assets/fonts/Inter-Italic-VariableFont_opsz,wght.ttf
